#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : voluptuous
Version  : 0.11.5
Release  : 23
URL      : https://files.pythonhosted.org/packages/6e/5e/4e721e30cf175f9e11a5acccf4cd74898c32cae93580308ecd4cf7d2a454/voluptuous-0.11.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/6e/5e/4e721e30cf175f9e11a5acccf4cd74898c32cae93580308ecd4cf7d2a454/voluptuous-0.11.5.tar.gz
Summary  : # Voluptuous is a Python data validation library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: voluptuous-python3
Requires: voluptuous-license
Requires: voluptuous-python
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-python

%description
# Voluptuous is a Python data validation library
[![Build Status](https://travis-ci.org/alecthomas/voluptuous.png)](https://travis-ci.org/alecthomas/voluptuous)
[![Coverage Status](https://coveralls.io/repos/github/alecthomas/voluptuous/badge.svg?branch=master)](https://coveralls.io/github/alecthomas/voluptuous?branch=master) [![Gitter chat](https://badges.gitter.im/alecthomas.png)](https://gitter.im/alecthomas/Lobby)

%package license
Summary: license components for the voluptuous package.
Group: Default

%description license
license components for the voluptuous package.


%package python
Summary: python components for the voluptuous package.
Group: Default
Requires: voluptuous-python3

%description python
python components for the voluptuous package.


%package python3
Summary: python3 components for the voluptuous package.
Group: Default
Requires: python3-core

%description python3
python3 components for the voluptuous package.


%prep
%setup -q -n voluptuous-0.11.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533134247
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/voluptuous
cp COPYING %{buildroot}/usr/share/doc/voluptuous/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/voluptuous/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
