#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : voluptuous
Version  : 0.11.1
Release  : 19
URL      : https://files.pythonhosted.org/packages/64/1a/bc658313d0a228ce474648c360bd06e28af3ed5e24029b1a4108739c23f4/voluptuous-0.11.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/64/1a/bc658313d0a228ce474648c360bd06e28af3ed5e24029b1a4108739c23f4/voluptuous-0.11.1.tar.gz
Summary  : Voluptuous is a Python data validation library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: voluptuous-python3
Requires: voluptuous-license
Requires: voluptuous-python
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools-python

%description
==============================================
        
        |Build Status| |Coverage Status| |Gitter chat|
        
        Voluptuous, *despite* the name, is a Python data validation library. It
        is primarily intended for validating data coming into Python as JSON,
        YAML, etc.

%package license
Summary: license components for the voluptuous package.
Group: Default

%description license
license components for the voluptuous package.


%package python
Summary: python components for the voluptuous package.
Group: Default
Requires: voluptuous-python3

%description python
python components for the voluptuous package.


%package python3
Summary: python3 components for the voluptuous package.
Group: Default
Requires: python3-core

%description python3
python3 components for the voluptuous package.


%prep
%setup -q -n voluptuous-0.11.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532361745
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/voluptuous
cp COPYING %{buildroot}/usr/share/doc/voluptuous/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/voluptuous/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
