#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : voluptuous
Version  : 0.8.9
Release  : 5
URL      : https://pypi.python.org/packages/source/v/voluptuous/voluptuous-0.8.9.tar.gz
Source0  : https://pypi.python.org/packages/source/v/voluptuous/voluptuous-0.8.9.tar.gz
Summary  : Voluptuous is a Python data validation library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: voluptuous-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Voluptuous is a Python data validation library
==============================================

%package python
Summary: python components for the voluptuous package.
Group: Default

%description python
python components for the voluptuous package.


%prep
%setup -q -n voluptuous-0.8.9

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
